version: "3.3"

services:
  mssql-server-windows-express:
    image: microsoft/mssql-server-windows-developer
    # volumes:
    #   - ./data:/var/opt/mssql
    ports:
      - "1433:1433"
    restart: always
    environment:
      sa_password: MySecretP@ssword$$
      ACCEPT_EULA: Y