version: "3.3"

services:
  mssql-server-windows-express:
    image: microsoft/mssql-server-windows-express
    # volumes:
    #   - ./data:C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL
    ports:
      - "1433:1433"
    restart: always
    environment:
      sa_password: MySecretP@ssword$$
      ACCEPT_EULA: Y
