version: "3.3"

services:
  mssql-server-linux-2019:
    container_name: mssql-linux-2019
    image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
    ports:
      - "1433:1433"
    restart: always
    network_mode: bridge
    environment:
      SA_PASSWORD: MySecretP@ssword$$
      MSSQL_PID: Developer
      ACCEPT_EULA: Y
